motoyaabe/coworking

app/assets/stylesheets/tops.scss
app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/helpers/operations_helper.rb
app/models/user.rb
app/views/layouts/_header.html.erb
app/views/operations/edit.html.erb
app/views/tops/_operation.html.erb
app/views/users/edit.html.erb
app/views/users/index.html.erb
config/environment.rb

> 概要
- ユーザー一覧作成
- ページネーション 作成・日本語化
- 検索機能追加・users.scssに追加
- ユーザー一覧表示

Operation 2

---

app/assets/stylesheets/users_new.scss
app/controllers/users_controller.rb
app/views/shared/_error_messages.html.erb
app/views/users/_form.html.erb
app/views/users/new.html.erb

ユーザー登録画面 更新

---

app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/helpers/users_helper.rb
app/views/layouts/_header.html.erb
app/views/layouts/application.html.erb
app/views/operations/edit.html.erb
app/views/users/_edit_info.html.erb
app/views/users/edit_info.js.erb
app/views/users/index.html.erb
config/environment.rb
config/routes.rb
db/seeds.rb

> 概要
- サンプルユーザー作成(６０名)
- 検索機能修正
- ページャー部の影響の問題
- ユーザー情報更新モーダル実装完了
- 利用状況部の定義は少々お待ちください。

ユーザー一覧修正＆ユーザー編集作成

---

app/assets/stylesheets/users.scss
app/assets/stylesheets/users_new.scss
app/views/users/_resavation_week.html.erb

詳細：ユーザー一覧ページャー表示修正
　　　予約画面カレンダー ボタン間延び修正

ユーザー一覧ページャーと予約画面カレンダー ボタン編集

---

app/models/user.rb
app/views/tops/_operation.html.erb

・ユーザー登録画面 バリデーション追加
・利用状況表示パーシャル 利用率からのプログレスバー表示切替

Regist list edit04

---

app/assets/javascripts/reservations.coffee
app/assets/stylesheets/reservations.scss
app/controllers/reservations_controller.rb
app/controllers/users_controller.rb
app/helpers/reservations_helper.rb
app/views/reservations/_edit.html.erb
app/views/reservations/edit.js.erb
app/views/users/index.html.erb
config/routes.rb
test/controllers/reservations_controller_test.rb

> 概要
- ユーザーdestroyアクション定義
- ユーザー一覧からのMS予約編集モーダルの作成をしたが途中で断念。

予約情報更新モーダル作成

---

app/assets/stylesheets/operations.scss
app/controllers/operations_controller.rb
app/models/operation.rb
app/views/operations/edit.html.erb
config/locales/ja.yml
config/locales/models/models_ja.yml

利用状況更新画面
レビュー指摘事項修正
・レイアウト
・フォーム作成
・表示情報

Operation edit

---

app/controllers/reservations_controller.rb
app/controllers/users_controller.rb
app/views/reservations/_new_user_reservation.html.erb

i have done modify . so please check it!!

Reservation

---

app/models/operation.rb
app/views/layouts/_header.html.erb
app/views/operations/edit.html.erb

URLを期待通りの挙動に修正。
更新ボタン不具合修正。
利用席数が総席数より多くならない様にバリデーション編集。

20190928完了

---

app/assets/stylesheets/custom.scss
app/views/layouts/_header.html.erb
app/views/users/index.html.erb
config/environment.rb

> 概要
- ユーザー一覧ページのhtmlの変更(渡邉さんのデザインに寄せた)
- ヘッダーの文字変更(html＆css)

ユーザー一覧ページ変更・ヘッダー変更

---

app/views/users/_form.html.erb
app/views/users/new.html.erb

ユーザー登録画面にデザインを実装しました。
レスポンシブ対応済みです。

ユーザー登録画面へのデザイン適用

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/reservations.scss
app/assets/stylesheets/users.scss
app/views/users/_reservation_week_tabale_th.html.erb
app/views/users/show.html.erb

ミーティングスペース予約画面の修正が完了しました。
内容
・application sassの修正
・bootstrap calendar をbootstrap4用に変更
・予約一覧画面に縦スクロールを追加

ミーティング予約画面の予約一覧縦スクロールとカレンダーのbootstrap4対応

---

app/assets/stylesheets/users.scss
app/views/sessions/new.html.erb
app/views/tops/home.html.erb
app/views/users/_edit_info.html.erb
app/views/users/index.html.erb
app/views/users/new.html.erb

ユーザーの登録一覧と更新画面にデザインを実装しました。
こちらの画面はco-ba様しか利用されない画面ということで、タブレット以上のサイズでレスポンシブ対応させています。

登録情報一覧・編集画面へデザインを実装

---

app/controllers/users_controller.rb
app/models/reservation.rb
app/views/reservations/_edit.html.erb
app/views/reservations/_new_user_reservation.html.erb
app/views/reservations/_show_user_reservation.html.erb
app/views/users/show.html.erb
config/locales/ja.yml
db/seeds.rb

モーダルの修正と、予約一覧の移動

---

app/models/reservation.rb
app/views/reservations/_edit.html.erb
app/views/users/index.html.erb

> 概要
- 不具合管理表NO,1→現在より過去の予約が存在する時は表示ボタンと日時を非表示にする。現在より未来の予約は表示ボタンと日時を表示にする。
- 不具合管理表NO,3→MS予約情報編集更新処理とエラーの訂正。

ユーザー一覧不具合訂正

---

app/assets/javascripts/application.js
app/assets/javascripts/operations.coffee
app/assets/javascripts/operations.js
app/assets/stylesheets/operations.scss
app/views/operations/edit.html.erb
config/application.rb

利用率更新画面へのデザインを実装しました。
タブレットまでのレスポンシブは適用済みです。

利用率更新画面へのデザイン適用

---

app/views/users/index.html.erb

予約情報編集モーダルの非表示処理

---

app/views/reservations/_edit.html.erb

予約情報編集画面にデザイン適用

---

Gemfile.lock
app/controllers/operations_controller.rb
app/models/operation.rb
app/views/operations/edit.html.erb
config/locales/ja.yml
db/migrate/20190829070650_create_operations.rb
db/schema.rb

・不備内容
No.5 URLを直で入力すると、管理者権限がなくても遷移
No.6 数字を物凄い桁数入れるとエラー
No.15 全席数と利用席数の入力欄が逆

20191022不備修正

---

app/views/reservations/_new_user_reservation.html.erb
app/views/users/_reservation_week_tabale_body.html.erb
app/views/users/show.html.erb

ミーティングスペース予約画面の修正が完了しましたので、確認をお願いいたします。

modify finish

---

app/controllers/reservations_controller.rb
app/models/user.rb
app/views/users/index.html.erb

> 概要
- NO.29 ユーザーモデルにバリデーションを追加。
- NO.28 LOGの予約時間の日付順にorderメソッドを追加。
- NO.19 予約削除後の遷移先をユーザー一覧に変更。

ユーザー一覧指摘事項修正

---

app/controllers/sessions_controller.rb

ログイン時にバリデーションエラーになった際、
入力値が保存されるようコードを追加しました。

ログインバリデーションエラー時に入力値を保存（不具合管理表No.24）

---

app/views/operations/edit.html.erb
db/migrate/20190829070650_create_operations.rb
db/schema.rb

①マイナスボタンでー表示にならないこと。
②1 席利用中/ 50席中(トップページと共通の方がわかりやすい)
③総席数は100程度でいい
以上の不備修正完了

Operation edit不備修正(No.30)

---

app/controllers/users_controller.rb

不具合管理表のNo.26を修正し、当日の予約一覧が表示できるようにしました。

予約状況一覧表示修正

---

app/models/operation.rb
app/views/operations/edit.html.erb

・利用席数の最大値に入力制限
・総席数の最小値に入力制限
・総席数のmax:100記述削除

20191028不備修正(上限値)

---

app/models/reservation.rb

validaitonの追加が完了しましたので、確認をお願いいたします。

validaiton add

---

app/views/layouts/application.html.erb

フラッシュメッセージにエスケープ処理が走るようにしました。
（不具合管理表No.31）

フラッシュメッセージのエスケープ処理を有効化

---

app/assets/stylesheets/custom.scss

ホーム画面のログインフォーム背景色のグレーを、
カラーコードを変更して適用させました。
適用前はシステムカラーでしたので、今回はシステムカラーではない色にしました。

ホーム画面のログインフォーム背景色を変更

---

app/controllers/reservations_controller.rb
app/controllers/users_controller.rb
app/views/layouts/application.html.erb
app/views/users/show.html.erb

下記の点について修正しました。
管理者ログイン時の予約一覧の表示
ユーザ一覧の表示順の修正
HTMLコードの無効化
（フォームから入力された文字列に含まれるHTMLコードの無効化とエラーの<br>の有効化を同時に行う方法が思いつかなかったため、エラー表示については、名前等を表示せずエラーのみ表示とし、登録が成功した時は、名前等を表示するようにしました。）

ユーザー一覧画面と予約一覧表示修正

---

app/views/reservations/_edit.html.erb
app/views/reservations/_new_user_reservation.html.erb
app/views/reservations/_show_user_reservation.html.erb

時間表示の間延び修正

---

app/views/reservations/_edit.html.erb
app/views/reservations/_new_user_reservation.html.erb
app/views/reservations/_show_user_reservation.html.erb

不具合管理表No.48
予約登録・編集・削除モーダル画面の「分」表記がされないのを修正

予約登録・編集・削除モーダルの「分」表記修正

---

app/views/operations/edit.html.erb

利用状況更新画面
・リセットボタン削除
・レイアウトの調整
完了いたしました。

20191109更新画面ボタン調整

---

app/views/users/index.html.erb

ユーザー一覧ヘッダーの日本語化

---

app/assets/stylesheets/reservations.scss
app/controllers/users_controller.rb
app/helpers/reservations_helper.rb
app/views/users/_reservation_week_tabale_body.html.erb
app/views/users/show.html.erb

タイムスケジュール表のスペースの修正が完了しました。
ご確認宜しくお願いします。

タイムスケジュール表のスペース修正

---

app/views/reservations/_new_user_reservation.html.erb

エラ〜メッセージセンター寄せ

---

app/views/reservations/_edit.html.erb
app/views/reservations/_new_user_reservation.html.erb

新規モーダル表示時のエラー表示の不具合を修正しました。
確認お願いします。

新規モーダルでのエラー表示不具合修正

---

app/views/reservations/_edit.html.erb
app/views/reservations/_new_user_reservation.html.erb

不具合管理表No.61の対応です。
削除ボタンの表示をわかりにくくしました。

削除ボタンの表示をわかりにくく変更

---

app/views/operations/edit.html.erb
app/views/users/index.html.erb

席更新画面とユーザー一覧画面でmb-5を追加
